<?php

/**
 * Application Language Lines - English
 * 
 * This file loads translations from the shared JSON file.
 * DO NOT EDIT THIS FILE. Edit resources/vue/locales/en.json instead.
 * 
 * Single source of truth: resources/vue/locales/en.json
 */

$jsonPath = resource_path('vue/locales/en.json');

if (!file_exists($jsonPath)) {
    throw new \RuntimeException("Translation file not found: {$jsonPath}");
}

$translations = json_decode(file_get_contents($jsonPath), true);

if (json_last_error() !== JSON_ERROR_NONE) {
    throw new \RuntimeException("Invalid JSON in translation file: " . json_last_error_msg());
}

return $translations;
