<?php

/**
 * Application Language Lines - Indonesian
 *
 * This file loads translations from the shared JSON file.
 * DO NOT EDIT THIS FILE. Edit lang/id.json instead.
 *
 * Single source of truth: lang/id.json
 */
$jsonPath = base_path('lang/id.json');

if (! file_exists($jsonPath)) {
    throw new \RuntimeException("Translation file not found: {$jsonPath}");
}

$translations = json_decode(file_get_contents($jsonPath), true);

if (json_last_error() !== JSON_ERROR_NONE) {
    throw new \RuntimeException('Invalid JSON in translation file: '.json_last_error_msg());
}

return $translations;
